In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN, LSTM, Dense

In [2]:
# Loading the IMDB Dataset
max_features = 10000 # Vocabulary Size
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=max_features)

# Print the Shape fo the Data
print(f"Trainig data shape : {X_train.shape},  Training Labels shape : {y_train.shape}")
print(f"Testing data shape : {X_test.shape},  Testing Labels shape : {y_test.shape}")

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 4s 0us/step
Trainig data shape : (25000,),  Training Labels shape : (25000,)
Testing data shape : (25000,),  Testing Labels shape : (25000,)


In [3]:
# Inspect a Sample Review and Its Label
Sample_review = X_train[0] # INput Features i.e Independent Features
Sample_label = y_train[0] # Output Features i.e Dependent Features
print(f"Sample Review : {Sample_review}")
print(f"Sample Label : {Sample_label}")

Sample Review : [1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]
Sample Label : 1


In [4]:
# Mapping of Words index back to Words(For Understanding)
word_index = imdb.get_word_index()
reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])

1641221/1641221 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [5]:
reverse_word_index # Here in these we see that data what the Particualr index is on it store

{34701: 'fawn',
 52006: 'tsukino',
 52007: 'nunnery',
 16816: 'sonja',
 63951: 'vani',
 1408: 'woods',
 16115: 'spiders',
 2345: 'hanging',
 2289: 'woody',
 52008: 'trawling',
 52009: "hold's",
 11307: 'comically',
 40830: 'localized',
 30568: 'disobeying',
 52010: "'royale",
 40831: "harpo's",
 52011: 'canet',
 19313: 'aileen',
 52012: 'acurately',
 52013: "diplomat's",
 25242: 'rickman',
 6746: 'arranged',
 52014: 'rumbustious',
 52015: 'familiarness',
 52016: "spider'",
 68804: 'hahahah',
 52017: "wood'",
 40833: 'transvestism',
 34702: "hangin'",
 2338: 'bringing',
 40834: 'seamier',
 34703: 'wooded',
 52018: 'bravora',
 16817: 'grueling',
 1636: 'wooden',
 16818: 'wednesday',
 52019: "'prix",
 34704: 'altagracia',
 52020: 'circuitry',
 11585: 'crotch',
 57766: 'busybody',
 52021: "tart'n'tangy",
 14129: 'burgade',
 52023: 'thrace',
 11038: "tom's",
 52025: 'snuggles',
 29114: 'francesco',
 52027: 'complainers',
 52125: 'templarios',
 40835: '272',
 52028: '273',
 52130: 'zaniacs',

In [6]:
decoded_review = ' '.join([reverse_word_index.get(i-3, '?') for i in Sample_review])
print(f"Decoded Review : {decoded_review}")
#

Decoded Review : ? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have d

In [7]:
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len = 500
X_train = sequence.pad_sequences(X_train, maxlen=max_len)
X_test = sequence.pad_sequences(X_test, maxlen=max_len)
X_train

array([[   0,    0,    0, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]])

In [8]:
X_train[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [9]:
# Train Simple RNN
model = Sequential()
model.add(Embedding(max_features, 128,input_length=max_len)) # Here it get all the Words and Convert into vectors with these 128 Dimension
model.add(SimpleRNN(128,activation='relu'))
model.add(Dense(1,activation='sigmoid'))


C:\Users\AKASH VISHWAKARMA\AppData\Roaming\Python\Python310\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
X_train[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [12]:
# Creating an Istance of EarlyStopping Callback
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
early_stopping

In [13]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# Traininf the Model with Early Stopping
history = model.fit(
    X_train, y_train,
    epochs=5,
    batch_size=32,
    validation_split=0.2,
    callbacks=[early_stopping]
)

Epoch 1/10
 39/625 ━━━━━━━━━━━━━━━━━━━━ 4:00 411ms/step - accuracy: 0.4955 - loss: 0.6931

KeyboardInterrupt: 

In [ ]:
# Save the MOdels
model.save('simple_rnn_model_imdb.h5')

# Predictions Start from Here or Create an Separate prediction.ipynb file




In [ ]:
model.get_weights()

[array([[-0.41646975,  0.24516921,  0.05500651, ..., -0.26963174,
         -0.4128836 ,  0.25219986],
        [-0.0635474 ,  0.00213362, -0.05848345, ...,  0.01031009,
         -0.01131779, -0.08723316],
        [-0.05419721, -0.09392206, -0.15272266, ...,  0.1358668 ,
          0.03163427, -0.19095789],
        ...,
        [-0.01247398,  0.01719153,  0.06643998, ..., -0.02557318,
          0.02611525,  0.05217327],
        [-0.00258224,  0.0352199 ,  0.04326546, ..., -0.06978165,
         -0.06481537, -0.02962356],
        [-0.07628103, -0.06388938,  0.09796754, ..., -0.03745861,
          0.04900397, -0.01318256]], dtype=float32),
 array([[-0.03111885,  0.19008456,  0.10963579, ..., -0.06768675,
         -0.10000837, -0.04663713],
        [ 0.1361498 ,  0.11781371,  0.17264514, ...,  0.14127614,
         -0.18605292, -0.11716592],
        [-0.19343838, -0.10260222, -0.02186684, ..., -0.13837078,
         -0.10545738,  0.05571223],
        ...,
        [ 0.1774655 ,  0.16539057, -0.1

In [ ]:
# Helper Function
# Function to Decode the Review
def decoded_review(encoded_review):
  return ' '.join([reverse_word_index.get(i-3, '?') for i in encoded_review])


# Function to Preprocess the User Input
def preprocess_text(text):
  words = text.lower().split()
  encoded_review = [word_index.get(word, 2)  + 3 for word in words]
  padded_review = sequence.pad_sequences([encoded_review], maxlen=500)
  return padded_review


In [ ]:
# Prediction FUnction
def predict_sentiment(review):
  preprocessed_review = preprocess_text(review)
  prediction = model.predict(preprocessed_review)
  sentiment = 'Positive' if prediction[0][0] > 0.5 else 'Negative'
  return sentiment,prediction[0][0]

In [ ]:
# Exmaple of the Review Preidctions
example_review = "The Moview is  really bad see the children due to showing the adult content in the moview."
sentiment,score = predict_sentiment(example_review)
print(f"Review : {example_review}")
print(f"Sentiment : {sentiment}")
print(f"Score : {score}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
Review : The Moview is  really bad see the children due to showing the adult content in the moview.
Sentiment : Negative
Score : 0.4344598948955536
